{% set version = "2.15.5" %}

package:
  name: nasm
  version: {{ version }}

source:
  fn: nasm-{{ version }}.tar.gz
  url: http://www.nasm.us/pub/nasm/releasebuilds/{{ version }}/nasm-{{ version }}.tar.xz
  sha256: 705a4bfbc8c958f1837a7e3c24c1adfd081154baed750006ec7a049b12b5525d

build:
  number: 1
  skip: true  # [win and vc<14]
  ignore_run_exports:
    - vc

requirements:
  build:
    - {{ compiler('c') }}
  host:
  run:
    - vs2015_runtime   # [win]

test:
  commands:
    - nasm -h
    - nasm -version
    - ndisasm -h

about:
  home: http://www.nasm.us
  license: BSD 2-Clause
  license_file: LICENSE
  summary: "Netwide Assembler: an assembler targetting the Intel x86 series of processors."

extra:
  recipe-maintainers:
    - jakirkham
